In [ ]:
# Solution of 01:
import numpy as np 
arr = np.arange(0,9)
print(arr)

[0 1 2 3 4 5 6 7 8]


In [ ]:
# Solution of 02:
import numpy as np
arr = np.random.randint(0,100,(4,4))
print(arr)

[[ 0 99 98 91]
 [78 66 46 22]
 [25 29 48 84]
 [54 84 52 68]]


In [18]:
# Solution of 03:
import numpy as np
arr = np.arange(20).reshape(4,5)
print(arr)

subarry = arr[1, 1:4]
print(subarry)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[6 7 8]


In [22]:
# Solution of 04:
import numpy as np
identitymatrix = np.eye(3)
print(identitymatrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [24]:
# Solution of 05:
import numpy as np
arr = np.random.rand( 2,3)
print(arr)

[[0.32394978 0.403243   0.42668461]
 [0.70073145 0.76808479 0.9587087 ]]


In [25]:
# Solution of 06:
import numpy as np
arr = np.random.rand(2,3).reshape(3,2)

print(arr)

[[0.34442618 0.78702257]
 [0.55199753 0.71208516]
 [0.13574075 0.53529576]]


In [26]:
# Solution of 07:
import numpy as np
arr = np.random.rand(5,5)
print(arr)

[[0.80343355 0.63972335 0.87361846 0.5780494  0.88285562]
 [0.86347971 0.15708658 0.73792737 0.38544093 0.63716962]
 [0.7876638  0.37784989 0.70896532 0.62433492 0.64222439]
 [0.27941962 0.44411185 0.41936034 0.49757176 0.65687332]
 [0.60704078 0.23344734 0.19059734 0.93541848 0.36854505]]


In [45]:
# Solution of 8:
import numpy as np

arr = np.arange(1, 13)     
matrix = arr.reshape(3, 4)  

print(matrix)




[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [46]:
# Solution of 12:
import numpy as np
arr1 = [[1,2,3],[4,5,6]]
arr2 = [[7,8,9],[10,11,12]]
concatenate = np.concatenate((arr1,arr2),axis=0)

print(concatenate)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
# Solution of 14:
import numpy as np
arr1 = [[1,2],[3,4]]
arr2 = [[5,6],[7,8]]
concatenate = np.concatenate((arr1,arr2),axis=1)

print(concatenate)

[[1 2 5 6]
 [3 4 7 8]]


In [48]:
# # Solution of 13:
import numpy as np
arr = np.zeros((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
